# Generated by Django 4.1.5 on 2023-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_completed',
            field=models.BooleanField(default=False),
        ),
    ]
