# Generated by Django 4.1.5 on 2023-02-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_refund_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_note',
        ),
    ]
